[candy_settings]
shorttext_length  = 80
showerror         = 1

icons_path        = 图标库
show_icon         = 1

[user_defined_texttype]
WebUrl            = i)^(https://|http://)?(\w+(-\w+)*\.)+[a-z]{2,}?
Email             = i)^[\w-_.]+@(?:\w+(?::\d+)?\.){1,3}(?:\w+\.?){1,2}$
MagnetLink        = i)^([a-z\d]){20,50}$

[texttype]
weburl            = run|%firefox% {text}||max
shorttext         = web|https://www.google.com/search?q={text:utf-8}
longtext          = web|https://www.google.com/search?q={text:utf-8}

[filetype]
;----特别的文件后缀-------------------------------------------------------
folder            = run|%ev% -path {file:fullpath}
drive             = %doublecmd% -path
noext             = %notepad%
multifiles        = run|%notepad% {"firstfile" "lastfile"}

url                                 = notepad.exe ||max

;----各类扩展名-------------------------------------------------------

acl|action|avs|avsi|bat|cal|cfg|cmd|cnf|cnx|conf|config|css|csv|gitconfig|gitignore|go|idx|inf|ini|js|jsee|json|list|lng|log|lrc|ltx|lua|markdown|md|md5|mkd|opml|po|pub|py|reg|regex|rule|sample|sed|session|settings|sh|sha|sol|tag|tex|tpl|txt|urllist|usr|utf-8|vbs|version|vim|xlb|xlc|xml|xsl|xspf|yaml|yml|zsh            = %notepad%

ahk                                 = menu|type-ahk

doc|docx|dotx|rtf|wps|wpt|odt|ott   = %workwpsoffice%
xls|xlsm|xlsx|et|ett|ods|ots        = %workwpsoffice%
ppt|pptx|dps|dpt|odp|otp            = %workwpsoffice%
ofd                                 = %worksuwellreader%

aac|aif|ape|au|cue|flac|m4a|mid|mp3|ogg|rmi|snd|wav|wma = menu|group-audio

3gp|avi|asf|blv|dat|flv|ifo|letv|m2t|m3u|mkv|mov|mp4|mpe|mpg|mpeg|rm|rmvb|swf|vob|webm|wmv = menu|group-video

ai|ani|apng|b3d|bmp|clp|cr2|crw|cur|dib|gif|ico|j2k|jng|jpeg|jpg|pcx|pgm|png|ppm|psd|psp|ras|raw|rle|rgb|sff|sgi|sid|sun|svg|tga|tif|tiff|wbmp|webp|wmf|xbm|xpm = menu|group-photo

htm|html|mht|mhtml|shtml|xhtml|url  = menu|group-webpage

xps|oxps|xod                        = %sumatrapdf%

pdf                                 = menu|type-pdf
gd                                  = %worksursenreader%

chm                                 = %chmreader%
pdi                                 = %photodemon%
