[candy_settings]
shorttext_length  = 80
showerror         = 1

icons_path        = 图标库
show_icon         = 1

[user_defined_texttype]
WebUrl            = i)^(https://|http://)?(\w+(-\w+)*\.)+[a-z]{2,}?
; Email             = i)^[\w-_.]+@(?:\w+(?::\d+)?\.){1,3}(?:\w+\.?){1,2}$
; MagnetLink        = i)^([a-z\d]){20,50}$

[texttype]
weburl            = run|%firefox% {text}||max
; shorttext         = web|https://www.google.com/search?q={text:utf-8}
; longtext          = web|https://www.google.com/search?q={text:utf-8}

[filetype]
;----特别的文件后缀-------------------------------------------------------
folder            = run|%doublecmd% -path {file:fullpath}
drive             = %doublecmd% -path
noext             = %vim%
multifiles        = run|%vim% {"firstfile" "lastfile"}

;----各类扩展名-------------------------------------------------------

doc|docx|dotx|rtf|wps|wpt|odt|ott   = %workwpsoffice%
xls|xlsm|xlsx|et|ett|ods|ots        = %workwpsoffice%
ppt|pptx|dps|dpt|odp|otp            = %workwpsoffice%

avs|avsi|bat|cfg|cmd|cnx|conf|config|css|csv|inf|ini|js|json|list|lng|log|lrc|lua|markdown|md|md5|mkd|opml|po|pub|py|reg|regex|rule|sample|sed|session|settings|sha|tex|tpl|txt|urllist|vbs|version|vim|xml|yaml|yml            = %vim%

ahk                                 = menu|type-ahk

avi|flv|m3u|mkv|mov|mp4|mpg|mpeg|webm|wmv = %mpchc%

aac|ape|au|cue|flac|m4a|mid|mp3|ogg|wav|wma = %mpchc%
ai|apng|bmp|gif|ico|jpeg|jpg|png|raw|svg|tif|tiff|wbmp|webp = menu|group-photo

chm                                 = %chmreader%
gd                                  = %worksursenreader%

htm|html|url                        = menu|group-webpage

pdi                                 = %photodemon%
pdf                                 = menu|type-pdf
ofd                                 = %worksuwellreader%

xps|oxps                            = %sumatrapdf%



