[General_Settings]
InUse_Browser      = firefox.exe,msedge.exe,chrome.exe,iexplore.exe
Default_Browser    = %firefox%
Default_TextEditor  = %vim%
MenuIconSize       = 14
MenuIconDir        = ini\icons

[TextEditor's_CommandLine]
vim                = --remote-silent-tab +$(LINENUM) "$(FILEPATH)"

[WebBrowser's_CommandLIne]
;chrome             = --user-data-dir=userdata --disk-cache-dir=cache --enable-easy-off-store-extension-install

[candy_hotkey]
;CapsLock          = ini\candy_TB14\candy-tb14.ini
CapsLock          = ini\candy_XX14\candy-xx14.ini
; !z          = ini\candy_XX14\candy-xx14.ini
; !z          = ini\candy_Work\candy-work.ini

[MyVar]
; 变量不能含有空格，也不能为空，不能包含点，否则，该条定义无效
; 具体规则，请参考ahk帮助，关于变量部分。
; 以下写法都是错误的。 
; mm.nn = xx.exe
; mm nn = xx.exe
; =xx.exe
; 
; 修改变量后，请重启脚本
; System-Tools

chmreader       = HH.exe
iexplore        = iexplore.exe
msedge          = msedge.exe
mspaint         = MSPaint.exe
notepad         = NotePad.exe

; Personal-Custom
wpsoffice       = ksolaunch.exe

aria2torrent    = D:\1-Program\0-CommandLineTools\Aria2\Aria2Torrent.exe
aria2task       = D:\1-Program\0-CommandLineTools\Aria2\Aria2Task.exe
qpdf            = D:\1-Program\0-CommandLineTools\QPDF\QPDF.bat

audacity        = D:\1-Program\Audacity\Audacity.exe
autohotkey      = D:\1-Program\AutoHotkey\AutoHotkey32.exe

doublecmd       = D:\1-Program\DoubleCMD\doublecmd.exe --no-splash -P L 

firefox         = D:\1-Program\Firefox\Core\firefox.exe
foobar2000      = D:\1-Program\Foobar2000\foobar2000.exe
irfanview       = D:\1-Program\IrfanView\i_view32.exe
keepass         = D:\1-Program\KeePass\KeePass.exe
mpchc           = D:\1-Program\MPC-HC\mpc-hc.exe
photodemon      = D:\1-Program\PhotoDemon\PhotoDemon.exe
sumatrapdf      = D:\1-Program\SumatraPDF\SumatraPDF.exe
vim             = D:\1-Program\Vim\vim91\gvim.exe

; Work-Custom
workchrome       = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
workfoxitreader  = C:\Program Files (x86)\Foxit Software\Foxit Reader\FoxitReader.exe
workistylepdf    = C:\Program Files (x86)\iWebPDF2018\iStylePDF.exe
worksursenreader = C:\Program Files (x86)\Sursen\Reader\SursenReader.exe
worksuwellreader = C:\Program Files (x86)\Suwell\Reader_Pro\SuwellReader.exe
workwpsoffice    = C:\Program Files (x86)\Kingsoft\WPS Office\ksolaunch.exe

