[custom]
exclude_remarks=过期时间|剩余流量|回国
udp_flag=true

rename_node=(移动|联通|电信|2组|隧道|专线)@
rename_node=CordCloud - @
rename_node=转@-

rename_node=Azure@AZ
rename_node=Cogent@CG
rename_node=Cera@CN
rename_node=HiNet@HN
rename_node=icable@IC
rename_node=Vodafone@VOD
rename_node=Webarena@WA
rename_node=商宽@B
rename_node=腾讯云@TC
rename_node=莫斯科@MOW
rename_node=新西伯利亚@OVB
rename_node=澳大利亚@澳洲

rename_node=\[倍率:(.*)\]@[$1倍]
rename_node=\[M\]\[(.*)\]@[$1M]
; rename_node=\[Trojan\].*\[(.*)倍@[$1倍T
rename_node=\[Trojan\].*\[(.*)倍@[$1倍

rename_node=深港@深圳-香港
rename_node=深圳-香港-@深港-
rename_node=广港@广港-香港

