[custom]
clash_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
loon_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
mellow_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
quan_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
quanx_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
sssub_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
surfboard_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl
surge_rule_base=https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/All-Base.tpl

exclude_remarks=回国
rename_node=(移动|联通|电信)@
rename_node=(2组|商宽)@
rename_node=隧道@
rename_node=莫斯科@MOW
rename_node=新西伯利亚@OVB
rename_node=\[M\]\[倍率:(.*)\]@[$1倍-M]
rename_node=\[倍率:(.*)\]@[$1倍]
;rename_node=- [Vv]2[Rr]ay@- V2

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraRejectFixDirect.list
ruleset=🌍 全球代理,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraRejectFixProxy.list

ruleset=🛑 全球拦截,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/More-Rule/Default-Reject.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraReject.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PrivateTracker.list

ruleset=📺 国内媒体,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/More-Rule/Default-Direct-Media.list
ruleset=📺 国内媒体,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/More-Rule/Video-Crack-Lite.list
ruleset=📺 国内媒体,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraDirectMedia.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/More-Rule/Default-Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraDirect.list

ruleset=🌍 全球代理,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/More-Rule/Default-Proxy.list
ruleset=🌍 全球代理,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraProxyMedia.list
ruleset=🌍 全球代理,https://raw.githubusercontent.com/JPLiu/TestFiles/main/Subconverter/ExtraProxy.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Download.list

ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]MATCH

custom_proxy_group=🔰 节点选择`select`[]♻️ 低倍测速`[]♻️ 高倍测速`[]🇭🇰 香港测速`[]🇭🇰 香港解锁`[]🇨🇳 台湾测速`[]🇨🇳 台湾解锁`[]🇺🇲 美国测速`[]🇺🇲 美国解锁`[]🇯🇵 日本测速`[]🇯🇵 日本解锁`[]🚀 手选节点
custom_proxy_group=📺 国内媒体`select`[]DIRECT`[]🔰 节点选择`[]🇭🇰 香港测速`[]🇭🇰 香港解锁`[]🇨🇳 台湾测速`[]🇨🇳 台湾解锁
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🔰 节点选择
custom_proxy_group=🌍 全球代理`select`[]🔰 节点选择`[]DIRECT
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT`[]🔰 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🔰 节点选择`[]DIRECT
custom_proxy_group=🚀 手选节点`select`(香港.*-M)`(香港)`(深港专线)`(台湾.*-M)`(台湾)`(美国.*-M)`(美国)`(日本.*-M)`(日本)`(新加坡.*-M)`(新加坡)`(-M)`.*
custom_proxy_group=♻️ 低倍测速`url-test`(\[0.*倍)`(\[1.*倍)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=♻️ 高倍测速`url-test`(\[2.*倍)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇭🇰 香港测速`url-test`(香港.*)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇭🇰 香港解锁`url-test`(香港.*-M)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇨🇳 台湾测速`url-test`(台湾.*)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇨🇳 台湾解锁`url-test`(台湾.*-M)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇺🇲 美国测速`url-test`(美国.*)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇺🇲 美国解锁`url-test`(美国.*-M)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇯🇵 日本测速`url-test`(日本.*)`http://www.gstatic.com/generate_204`180,5,60
custom_proxy_group=🇯🇵 日本解锁`url-test`(日本.*-M)`http://www.gstatic.com/generate_204`180,5,60

clash_use_new_field_name=true
enable_rule_generator=true
filter_deprecated_nodes=true
overwrite_original_rules=true

[template]
;clash.mixed_port=7890
;clash.redir_port=7892
;clash.allow_lan=true
;clash.log_level=info
;clash.api_port=127.0.0.1:9090
;clash.api_externalui=Dashboard

