[candy_settings]
shorttext_length  = 80
showerror         = 1

icons_path        = 图标库
show_icon         = 1

[user_defined_texttype]
WebUrl            = i)^(https://|http://)?(\w+(-\w+)*\.)+[a-z]{2,}?
Email             = i)^[\w-_.]+@(?:\w+(?::\d+)?\.){1,3}(?:\w+\.?){1,2}$
MagnetLink        = i)^([a-z\d]){20,50}$

[texttype]
weburl            = run|%firefox% {text}||max
shorttext         = web|https://www.google.com/search?q={text:utf-8}
longtext          = web|https://www.google.com/search?q={text:utf-8}
magnetlink        = run|%aria2task% {text}||max

[filetype]
;----特别的文件后缀-------------------------------------------------------
folder            = run|%ev% -path {file:fullpath}
drive             = %doublecmd% -path
noext             = %notepad%
multifiles        = run|%notepad% {"firstfile" "lastfile"}

;----各类扩展名-------------------------------------------------------

doc|docx|dotx|rtf|wps|wpt|odt|ott   = %wpsoffice%
xls|xlsm|xlsx|et|ett|ods|ots        = %wpsoffice%
ppt|pptx|dps|dpt|odp|otp            = %wpsoffice%

avi|flv|m3u|mkv|mov|mp4|mpg|mpeg|webm|wmv = menu|group-video
aac|ape|au|cue|flac|m4a|mid|mp3|ogg|wav|wma = menu|group-audio
bat|cfg|cmd|cnx|conf|config|css|csv|inf|ini|js|json|list|lng|log|lrc|lua|markdown|md|md5|mkd|opml|po|pub|py|reg|regex|rule|sample|sed|session|settings|sha|tex|tpl|txt|urllist|vbs|version|vim|xml|yaml|yml            = %notepad%
ahk                                 = menu|type-ahk
avs|avsi                            = menu|type-avs
ai|apng|bmp|gif|ico|jpeg|jpg|png|raw|svg|tif|tiff|wbmp|webp = menu|group-photo
cb7z|cbr|cbt|cbz                    = %sumatrapdf%

chm                                 = %chmreader%
djv|djvu                            = %sumatrapdf%
epub|mobi                           = menu|group-ebook

htm|html|url                        = menu|group-webpage
kdbx                                = %keepass%

ofd                                 = %wpsoffice%
pdf                                 = menu|type-pdf
pdi                                 = %photodemon%
torrent                             = %aria2torrent%

xps|oxps                            = %sumatrapdf%
